import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Apple iPhone",
  description: "Generated by Ahmed Baloch",
  icons: [
       {
          url:'/public/assets/images/apple.svg',
          href:'/public/assets/images/apple.svg'
        }
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// icons:[
//   {
//     url:'/logo1.svg',
//     href:'/logo1.svg'
//   }
// ]